### ISSUE TITLE
[Suggestion] Remember time as well?

### ISSUE THREAD

**Issue by j2nik** [gagizagi/KissAnimePlusPlus#1]
Hey man, think you could make it so that the extension makes it so that it remembers where I left off the video? Say Im watching something, close my computer when the video is at 12:12, and then I turn on my PC, open the same video [link] it goes back to 12:12.

**Comment by gagizagi** [comment]
Pretty good idea actually. Should be easy to add too. I'll see if I can find some time this week

**Comment by j2nik** [comment]
Pretty damn sweet if you'd manage to add it, I'd use Netflix much less then

**Comment by gagizagi** [comment]
Updated so it remembers time aswell and improved some of the old code.
Also made it work for KissCartoon and KissAsia aswell.
Please let me know if there are any issues or if you have have further ideas ;)

**Comment by j2nik** [comment]
Wow this is so good, thank you so much. One thing though, it doesn't seem to sync between computers. Is there any way to fix that?

I'll add some more suggestions later!

**Comment by gagizagi** [comment]
Looked into it briefly and there seems to be a way to save it on google account. 
Never did anything like it before though so i'll have to research it abit over the weekend and see how viable it is. 

I also got a few really cool ideas while working on it today, but they are bigger projects so i'll probably just make a new extension for those at first.

**Comment by gagizagi** [comment]
New version (2.2) saves to chrome cloud storage, so it _should_ work across different machines that use the same chrome account.

**Comment by j2nik** [comment]
I have a pretty good suggestion, left to the "Turn off the light" button, add some kind of new Maximize button where the player turns full screen (but only in the tab). Like this on youtube:

https://i.imgur.com/kgEmi80.png
